CompileFlags:
	Add: [-W, -Wall, -pedantic, -D=_CRT_SECURE_NO_WARNINGS]

---

If:
	PathMatch: .*\.h
CompileFlags:
	Add: [-xc-header]

---

If:
	PathMatch: .*\.c
CompileFlags:
	Add: [-xc]

---

If:
	PathMatch: .*\.hpp
CompileFlags:
	Add: [-xc++-header]

---

If:
	PathMatch: .*\.cpp
CompileFlags:
	Add: [-xc++]
